### ISSUE TITLE
Only run nosetests when there actually are python unit tests

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_tools#117]
## The problem
Currently when calling `enable_bitbtos_tests()` it will always call `catkin_add_nosetests()` even when there are not actually any python unit tests available. This results in nosetest being executed and returning that all (0 of 0) tests have passed which is essentially useless information.

## Possible solution
The `enable_bitbots_test()` cmake function already knows if there are python unit tests defined because it checks if they are executable. It should therefore be easy to simply not call `catkin_add_nosetests()` when the list of discovered python unit tests is empty.

**Comment by Flova** [comment]
Outdated
