### ISSUE TITLE
`MockSubscriber.wait_until_connected()` should have a timeout

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_tools#119]
## Problem
Sometimes an issue arrises that no node connects to the `MockSubscriber` however there currently is no assertion for the number of subscribers and `wait_until_connected()` does not ever exit in that error case.

## Possible solution
`MockSubscriber.wait_until_connected()` should accept a timeout argument with sensible default.

**Comment by Flova** [comment]
Outdated
