### ISSUE TITLE
CMake FILE TOUCH unsupported in Ubuntu 18.04

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_tools#2]
Ubuntu comes with cmake 3.10.2, the `FILE TOUCH` cmake command was introduced in version 3.11. `FILE WRITE` can be used instead.

**Comment by ftsell** [comment]
I see your point but I cannot find any usages of `FILE TOUCH`. Where did you see it?

**Comment by timonegk** [comment]
It had been present in the old bitbots_tools in bitbots_misc. I thought that the code was just moved but apparently some changes were made including fixing this.
