### ISSUE TITLE
translate docs to english

### ISSUE THREAD

**Issue by ftsell** [bit-bots/bitbots_tools#5]

**Comment by flechnical** [comment]
Hi, ich würde im Sinne des Hacktoberfest gerne eine Übersetzung zu eurem Projekt beitragen. Wäre es von euch gewünscht, wenn ich z.B. bitbots_docs/docs/manual/tutorials/animation.rst auf Englisch übersetze?

Wäre es evtl. besser, wenn ich gleich einen neuen Ordner "English" in den docs erstelle, und die Übersetzung da reinsetze, damit die deutsche Version nicht rausgenommen wird?

**Comment by NFiedler** [comment]
Wir haben kein Problem damit, wenn die deutsche Version raus ist. Vor Allem, weil wir sonst die deutsche und englische gleichzeitig maintainen müssten, was mit hoher wahrscheinlichkeit in die Hose geht :sweat_smile: 
Bei weiteren Fragen melde dich gern!
