### ISSUE TITLE
Ansible Updates

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_tools#54]
For compute stick:
MTU size auf NUC setzen,
OpenVino auf allen Nucs installieren und Source in zshrc

**Comment by ftsell** [comment]
@Flova since the intel download site does not currently work ( https://software.seek.intel.com/openvino-toolkit?os=linux ) can you please provide me with an openvino .tar.gz file?

**Comment by Flova** [comment]
Is this still a thing? @ftsell The site seems to work for me.

**Comment by timonegk** [comment]
This is done already, see our `ansible_robot` git.
